import SwiftUI

struct ConversationOnboardingView: View {
    @State private var showGoodToKnow = false

    var body: some View {
        ScrollView {
            VStack(spacing: 24) {
                Spacer(minLength: 40)

                // Important banner
                HStack(alignment: .top, spacing: 8) {
                    Image(systemName: "exclamationmark.triangle.fill")
                        .foregroundStyle(.orange)
                        .font(.caption)
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Important")
                            .font(.caption.weight(.semibold))
                            .foregroundStyle(.orange)
                        Text("Chat responses are generated by AI and are not medical advice.")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(10)
                .background(
                    RoundedRectangle(cornerRadius: 8)
                        .fill(Color.orange.opacity(0.08))
                )

                // Main card (matches web layout)
                VStack(spacing: 20) {
                    // Header
                    VStack(spacing: 12) {
                        Image(systemName: "ellipsis.message")
                            .font(.largeTitle)
                            .imageScale(.large)
                            .foregroundStyle(Color.accentColor)
                            .accessibilityHidden(true)

                        Text("Start a Care Session")
                            .font(.title2.weight(.semibold))

                        Text("Share a bit about the patient, their history, and the current situation. Don’t worry about being perfect—just type what’s on your mind.")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                            .multilineTextAlignment(.center)
                            .padding(.horizontal, 16)
                    }
                    .padding(.top, 8)

                    Divider()

                    // Good to Know
                    VStack(spacing: 0) {
                        Button {
                            withAnimation(.spring(duration: 0.3)) {
                                showGoodToKnow.toggle()
                            }
                        } label: {
                            HStack {
                                Image(systemName: "info.circle")
                                    .foregroundStyle(Color.accentColor)
                                Text("Good to know")
                                    .font(.subheadline.weight(.semibold))
                                    .foregroundStyle(.primary)
                                Text("· \(showGoodToKnow ? "hide" : "show")")
                                    .font(.subheadline)
                                    .foregroundStyle(.secondary)
                            }
                            .frame(maxWidth: .infinity)
                            .padding(.horizontal, 4)
                        }

                        if showGoodToKnow {
                            VStack(alignment: .leading, spacing: 10) {
                                infoRow(icon: "person.2", text: "Bring others into a care session via the people icon at the top right of chat")
                                infoRow(icon: "gearshape", text: "Rename, recolor, or delete care sessions in Settings → Your Care Sessions")
                                infoRow(icon: "bolt.fill", text: "AI generates your Daily Digest and Care Journal automatically")
                                infoRow(icon: "folder", text: "View files in Document Manager and Audio Recordings (upload multiple at once)")
                                infoRow(icon: "book", text: "Learn more about AretaCare in Settings → Support → About AretaCare")
                            }
                            .frame(maxWidth: .infinity, alignment: .leading)
                            .padding(.top, 10)
                            .padding(.horizontal, 4)
                            .transition(.opacity.combined(with: .move(edge: .top)))
                        }
                    }

                    Divider()

                    // Input hints
                    HStack(spacing: 20) {
                        Label("Message", systemImage: "text.bubble")
                        Label("Attach", systemImage: "paperclip")
                        Label("Record", systemImage: "mic.fill")
                    }
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .padding(.bottom, 4)
                }
                .padding(20)
                .background(Color(.secondarySystemGroupedBackground))
                .clipShape(RoundedRectangle(cornerRadius: 16))
                .overlay(
                    RoundedRectangle(cornerRadius: 16)
                        .strokeBorder(Color.accentColor.opacity(0.2), lineWidth: 1)
                )

                Spacer(minLength: 20)
            }
            .padding(.horizontal)
        }
    }

    private func infoRow(icon: String, text: String) -> some View {
        HStack(alignment: .top, spacing: 10) {
            Image(systemName: icon)
                .font(.footnote)
                .foregroundStyle(Color.accentColor)
                .frame(width: 20)
            Text(text)
                .font(.footnote)
                .foregroundStyle(.primary)
        }
    }
}
