import SwiftUI

struct ConversationOnboardingView: View {
    @State private var showGoodToKnow = false

    var body: some View {
        ScrollView {
            VStack(spacing: 24) {
                Spacer(minLength: 40)

                // Important banner
                HStack(alignment: .top, spacing: 8) {
                    Image(systemName: "exclamationmark.triangle.fill")
                        .foregroundStyle(.orange)
                        .font(.caption)
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Important")
                            .font(.caption.weight(.semibold))
                            .foregroundStyle(.orange)
                        Text("Chat responses are generated by AI and are not medical advice.")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(10)
                .background(
                    RoundedRectangle(cornerRadius: 8)
                        .fill(Color.orange.opacity(0.08))
                )

                // Main card (matches web layout)
                VStack(spacing: 20) {
                    // Header
                    VStack(spacing: 12) {
                        Image(systemName: "ellipsis.message")
                            .font(.system(size: 44))
                            .foregroundStyle(Color.accentColor)

                        Text("Start a Conversation")
                            .font(.title2.weight(.semibold))

                        Text("Tell us what's happening and how we can help")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                            .multilineTextAlignment(.center)
                            .padding(.horizontal, 16)
                    }
                    .padding(.top, 8)

                    Divider()

                    // Good to Know
                    VStack(alignment: .leading, spacing: 0) {
                        Button {
                            withAnimation(.easeInOut(duration: 0.25)) {
                                showGoodToKnow.toggle()
                            }
                        } label: {
                            HStack {
                                Image(systemName: "info.circle")
                                    .foregroundStyle(Color.accentColor)
                                Text("Good to know")
                                    .font(.subheadline.weight(.medium))
                                    .foregroundStyle(.primary)
                                Text("· \(showGoodToKnow ? "hide" : "show")")
                                    .font(.subheadline)
                                    .foregroundStyle(.secondary)
                                Spacer()
                            }
                            .padding(.horizontal, 4)
                        }

                        if showGoodToKnow {
                            VStack(alignment: .leading, spacing: 10) {
                                infoRow(icon: "person.2", text: "Bring others into the conversation under Collaboration")
                                infoRow(icon: "gearshape", text: "Rename or delete this session in Settings \u{2192} Manage Sessions")
                                infoRow(icon: "bolt", text: "AI generates your Daily Digest and Care Journal automatically")
                                infoRow(icon: "folder", text: "View your files in Document Manager and Audio Recordings")
                                infoRow(icon: "book.closed", text: "Learn more about AretaCare on the About page")
                            }
                            .padding(.top, 10)
                            .padding(.horizontal, 4)
                            .transition(.opacity.combined(with: .move(edge: .top)))
                        }
                    }

                    Divider()

                    // Footer
                    VStack(spacing: 6) {
                        (Text("Type a message, ")
                         + Text(Image(systemName: "paperclip"))
                         + Text(" upload documents, or ")
                         + Text(Image(systemName: "mic.fill"))
                         + Text(" record audio"))
                            .font(.caption)
                            .foregroundStyle(.secondary)
                            .multilineTextAlignment(.center)

                        Image(systemName: "arrow.down")
                            .font(.caption)
                            .foregroundStyle(Color.accentColor)
                    }
                    .padding(.bottom, 4)
                }
                .padding(20)
                .background(Color(.secondarySystemGroupedBackground))
                .clipShape(RoundedRectangle(cornerRadius: 16))
                .overlay(
                    RoundedRectangle(cornerRadius: 16)
                        .strokeBorder(Color.accentColor.opacity(0.2), lineWidth: 1)
                )

                Spacer(minLength: 20)
            }
            .padding(.horizontal)
        }
    }

    private func infoRow(icon: String, text: String) -> some View {
        HStack(alignment: .top, spacing: 10) {
            Image(systemName: icon)
                .font(.caption)
                .foregroundStyle(Color.accentColor)
                .frame(width: 20)
            Text(text)
                .font(.caption)
                .foregroundStyle(.secondary)
        }
    }
}
