import SwiftUI

struct ConversationOnboardingView: View {
    @State private var showGoodToKnow = false

    var body: some View {
        ScrollView {
            VStack(spacing: 24) {
                Spacer(minLength: 40)

                // Important banner
                HStack(alignment: .top, spacing: 8) {
                    Image(systemName: "exclamationmark.triangle.fill")
                        .foregroundStyle(.orange)
                        .font(.caption)
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Important")
                            .font(.caption.weight(.semibold))
                            .foregroundStyle(.orange)
                        Text("Chat responses are generated by AI and are not medical advice.")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(10)
                .background(
                    RoundedRectangle(cornerRadius: 8)
                        .fill(Color.orange.opacity(0.08))
                )

                // Main card (matches web layout)
                VStack(spacing: 20) {
                    // Header
                    VStack(spacing: 12) {
                        Image(systemName: "ellipsis.message")
                            .font(.system(size: 44))
                            .foregroundStyle(Color.accentColor)

                        Text("Start a Conversation")
                            .font(.title2.weight(.semibold))

                        Text("Tell us what's happening and how we can help")
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                            .multilineTextAlignment(.center)
                            .padding(.horizontal, 16)
                    }
                    .padding(.top, 8)

                    Divider()

                    // Good to Know
                    VStack(spacing: 0) {
                        Button {
                            withAnimation(.spring(duration: 0.3)) {
                                showGoodToKnow.toggle()
                            }
                        } label: {
                            HStack {
                                Image(systemName: "info.circle")
                                    .foregroundStyle(Color.accentColor)
                                Text("Good to know")
                                    .font(.subheadline.weight(.medium))
                                    .foregroundStyle(.primary)
                                Text("· \(showGoodToKnow ? "hide" : "show")")
                                    .font(.subheadline)
                                    .foregroundStyle(.secondary)
                            }
                            .padding(.horizontal, 4)
                        }

                        if showGoodToKnow {
                            VStack(alignment: .leading, spacing: 10) {
                                infoRow(icon: "list.bullet", text: "Create and switch between sessions using the chat menu")
                                infoRow(icon: "doc.text.magnifyingglass", text: "AI generates your daily digest automatically")
                                infoRow(icon: "wrench.and.screwdriver", text: "View care journal, documents, recordings, and health profile in Tools")
                                infoRow(icon: "gear", text: "Add collaborators, rename, and delete sessions in Settings")
                            }
                            .frame(maxWidth: .infinity, alignment: .leading)
                            .padding(.top, 10)
                            .padding(.horizontal, 4)
                            .transition(.opacity.combined(with: .move(edge: .top)))
                        }
                    }

                    Divider()

                    // Input hints
                    HStack(spacing: 20) {
                        Label("Message", systemImage: "text.bubble")
                        Label("Attach", systemImage: "paperclip")
                        Label("Record", systemImage: "mic.fill")
                    }
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .padding(.bottom, 4)
                }
                .padding(20)
                .background(Color(.secondarySystemGroupedBackground))
                .clipShape(RoundedRectangle(cornerRadius: 16))
                .overlay(
                    RoundedRectangle(cornerRadius: 16)
                        .strokeBorder(Color.accentColor.opacity(0.2), lineWidth: 1)
                )

                Spacer(minLength: 20)
            }
            .padding(.horizontal)
        }
    }

    private func infoRow(icon: String, text: String) -> some View {
        HStack(alignment: .top, spacing: 10) {
            Image(systemName: icon)
                .font(.caption)
                .foregroundStyle(Color.accentColor)
                .frame(width: 20)
            Text(text)
                .font(.caption)
                .foregroundStyle(.secondary)
        }
    }
}
