#!/bin/bash
set -e

echo "Running ci_post_clone.sh..."

# Install XcodeGen and generate .xcodeproj
brew install xcodegen
cd "$CI_PRIMARY_REPOSITORY_PATH/ios"
xcodegen generate
echo "Generated AretaCare.xcodeproj"

# Copy Package.resolved into the generated xcodeproj so Xcode Cloud finds it
RESOLVED_DIR="$CI_PRIMARY_REPOSITORY_PATH/ios/AretaCare.xcodeproj/project.xcworkspace/xcshareddata/swiftpm"
mkdir -p "$RESOLVED_DIR"
cp "$CI_PRIMARY_REPOSITORY_PATH/ios/Package.resolved" "$RESOLVED_DIR/Package.resolved"
echo "Copied Package.resolved"

cd "$CI_PRIMARY_REPOSITORY_PATH"

# Create Secrets.xcconfig with CI environment variables
# Note: DEVELOPMENT_TEAM is handled automatically by Xcode Cloud code signing
SECRETS_PATH="$CI_PRIMARY_REPOSITORY_PATH/ios/AretaCare/Configuration/Secrets.xcconfig"
echo "// Generated by Xcode Cloud" > "$SECRETS_PATH"
if [ -n "$REVENUECAT_API_KEY" ]; then
    echo "REVENUECAT_API_KEY = $REVENUECAT_API_KEY" >> "$SECRETS_PATH"
fi

# Override URLs based on branch
RELEASE_CONFIG="$CI_PRIMARY_REPOSITORY_PATH/ios/AretaCare/Configuration/Release.xcconfig"

if [ "$CI_BRANCH" = "main" ]; then
    # Production — Release.xcconfig already has production URLs, no changes needed
    echo "Branch: main — using production URLs"
else
    # Staging — override Release.xcconfig URLs
    sed -i '' "s|API_BASE_URL = .*|API_BASE_URL = https:/\$()/staging.aretacare.com/api|" "$RELEASE_CONFIG"
    sed -i '' "s|FRONTEND_URL = .*|FRONTEND_URL = https:/\$()/staging.aretacare.com|" "$RELEASE_CONFIG"
    echo "Branch: $CI_BRANCH — using staging URLs"
fi
