#!/bin/bash
set -e

echo "Running ci_post_clone.sh..."

# Install XcodeGen and generate .xcodeproj
brew install xcodegen
cd "$CI_PRIMARY_REPOSITORY_PATH/ios"
xcodegen generate
echo "Generated AretaCare.xcodeproj"

# The SPM lockfile is tracked at AretaCare.xcodeproj/project.xcworkspace/xcshareddata/
# swiftpm/Package.resolved, and xcodegen leaves it in place. Don't copy another lockfile
# over it: that is the file Dependabot updates, so an overwrite silently reverts its bumps.

cd "$CI_PRIMARY_REPOSITORY_PATH"

# Create Secrets.xcconfig with CI environment variables
# Note: DEVELOPMENT_TEAM is handled automatically by Xcode Cloud code signing
SECRETS_PATH="$CI_PRIMARY_REPOSITORY_PATH/ios/AretaCare/Configuration/Secrets.xcconfig"
echo "// Generated by Xcode Cloud" > "$SECRETS_PATH"
if [ -n "$REVENUECAT_API_KEY" ]; then
    echo "REVENUECAT_API_KEY = $REVENUECAT_API_KEY" >> "$SECRETS_PATH"
fi
if [ -n "$SENTRY_DSN" ]; then
    # xcconfig treats // as a comment — escape the DSN's :// with the $()
    # trick (same as the URL overrides below) or it gets silently truncated.
    echo "SENTRY_DSN = $(echo "$SENTRY_DSN" | sed 's|://|:/$()/|')" >> "$SECRETS_PATH"
fi

# Override URLs based on branch
RELEASE_CONFIG="$CI_PRIMARY_REPOSITORY_PATH/ios/AretaCare/Configuration/Release.xcconfig"

if [ "$CI_BRANCH" = "main" ]; then
    echo "SENTRY_ENVIRONMENT = production" >> "$SECRETS_PATH"
    echo "Branch: main — using production URLs"
else
    # Staging — override Release.xcconfig URLs
    sed -i '' "s|API_BASE_URL = .*|API_BASE_URL = https:/\$()/staging-api.aretacare.com/api|" "$RELEASE_CONFIG"
    sed -i '' "s|FRONTEND_URL = .*|FRONTEND_URL = https:/\$()/staging.aretacare.com|" "$RELEASE_CONFIG"
    echo "SENTRY_ENVIRONMENT = staging" >> "$SECRETS_PATH"
    echo "Branch: $CI_BRANCH — using staging URLs"
fi
